# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 1020)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QFrame(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(10, 10, 1311, 941))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Image.setFont(font)
        self.Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image.setObjectName("Image")
        self.label = QtWidgets.QLabel(self.Image)
        self.label.setGeometry(QtCore.QRect(240, 20, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnLoadData = QtWidgets.QPushButton(self.Image)
        self.btnLoadData.setGeometry(QtCore.QRect(670, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadData.setFont(font)
        self.btnLoadData.setObjectName("btnLoadData")
        self.btnProses = QtWidgets.QPushButton(self.Image)
        self.btnProses.setGeometry(QtCore.QRect(820, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnProses.setFont(font)
        self.btnProses.setObjectName("btnProses")
        self.label_3 = QtWidgets.QLabel(self.Image)
        self.label_3.setGeometry(QtCore.QRect(160, 510, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Image)
        self.label_4.setGeometry(QtCore.QRect(600, 510, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Image)
        self.label_5.setGeometry(QtCore.QRect(990, 510, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputDataUji = QtWidgets.QTextEdit(self.Image)
        self.inputDataUji.setGeometry(QtCore.QRect(40, 100, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inputDataUji.setFont(font)
        self.inputDataUji.setObjectName("inputDataUji")
        self.label_7 = QtWidgets.QLabel(self.Image)
        self.label_7.setGeometry(QtCore.QRect(50, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.Image)
        self.label_2.setGeometry(QtCore.QRect(40, 560, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_asli = QtWidgets.QLabel(self.Image)
        self.label_asli.setGeometry(QtCore.QRect(100, 160, 230, 320))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_asli.setFont(font)
        self.label_asli.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_asli.setText("")
        self.label_asli.setPixmap(QtGui.QPixmap(":/picture/11204-200.png"))
        self.label_asli.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asli.setObjectName("label_asli")
        self.label_roi = QtWidgets.QLabel(self.Image)
        self.label_roi.setGeometry(QtCore.QRect(480, 180, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_roi.setFont(font)
        self.label_roi.setText("")
        self.label_roi.setPixmap(QtGui.QPixmap(":/picture/11204-200.png"))
        self.label_roi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roi.setObjectName("label_roi")
        self.label_gray = QtWidgets.QLabel(self.Image)
        self.label_gray.setGeometry(QtCore.QRect(890, 190, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gray.setFont(font)
        self.label_gray.setText("")
        self.label_gray.setPixmap(QtGui.QPixmap(":/picture/11204-200.png"))
        self.label_gray.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gray.setObjectName("label_gray")
        self.btnEigen = QtWidgets.QPushButton(self.Image)
        self.btnEigen.setGeometry(QtCore.QRect(970, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEigen.setFont(font)
        self.btnEigen.setObjectName("btnEigen")
        self.btnUji = QtWidgets.QPushButton(self.Image)
        self.btnUji.setGeometry(QtCore.QRect(1120, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnUji.setFont(font)
        self.btnUji.setObjectName("btnUji")
        self.textUji = QtWidgets.QTextEdit(self.Image)
        self.textUji.setGeometry(QtCore.QRect(370, 570, 500, 351))
        self.textUji.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.textUji.setObjectName("textUji")
        self.label_6 = QtWidgets.QLabel(self.Image)
        self.label_6.setGeometry(QtCore.QRect(190, 720, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.Image)
        self.label_8.setGeometry(QtCore.QRect(140, 750, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Image)
        self.label_9.setGeometry(QtCore.QRect(280, 700, 21, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1322, 21))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuHome.addAction(self.actionexit)
        self.menubar.addAction(self.menuHome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interface Program"))
        self.label.setText(_translate("MainWindow", "KLASIFIKASI WAJAH MENGGUNAKAN K-NN"))
        self.btnLoadData.setText(_translate("MainWindow", "Load"))
        self.btnProses.setText(_translate("MainWindow", "Proses"))
        self.label_3.setText(_translate("MainWindow", "Citra Asli"))
        self.label_4.setText(_translate("MainWindow", "ROI"))
        self.label_5.setText(_translate("MainWindow", "Grayscale"))
        self.label_7.setText(_translate("MainWindow", "Load Data Uji"))
        self.btnEigen.setText(_translate("MainWindow", "Eigen"))
        self.btnUji.setText(_translate("MainWindow", "Pengujian"))
        self.label_6.setText(_translate("MainWindow", "HASIL "))
        self.label_8.setText(_translate("MainWindow", "PENGUJIAN"))
        self.label_9.setText(_translate("MainWindow", ":"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.actionexit.setText(_translate("MainWindow", "exit"))

import arrow_rc
import note_rc
import picture_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

